# Generated by Django 3.2.3 on 2021-05-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='port',
            field=models.IntegerField(default=8000),
        ),
    ]
