# Generated by Django 3.2.3 on 2021-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_alter_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
